### ISSUE TITLE
Very cool project ! But may you make it support x86 architecture.

### ISSUE THREAD

**Issue by FireC672** [msvisser/BrainfuckJIT-ARM#1]
I was searching a **Brainfuck** to **machine-code** program, I found yours, but my computer doesn't have the ARM instruction, can I know if you can make it support the x86 or no ? 

anyways, I really enjoy this project, I found joy in disassembling, and i'am trying to configure it for x86.

**Comment by msvisser** [comment]
It would certainly be possible to add x86 support, however I'm not planning to add support. You can look at replacing the generated machine code with x86 instructions, which should be fairly easy as every instruction is commented.
